[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
size = 10

[colors.primary]
background = "0xffffff"
foreground = "0x2c2c2c"

[colors.normal]
black = "0x45475a"
red = "0xf38ba8"
green = "0xa6e3a1"
yellow = "0xf9e2af"
blue = "0x89b4fa"
magenta = "0xf5c2e7"
cyan = "0x4a4a4a"
white = "0xb4befe"

[colors.bright]
black = "0x585b70"
red = "0xf38ba8"
green = "0xa6e3a1"
yellow = "0xf9e2af"
blue = "0x89b4fa"
magenta = "0xf5c2e7"
cyan = "0x4a4a4a"
white = "0xa6adc8"

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 10, y = 10 }

