[urgency_low]
    background = "#282828"
    foreground = "#ebdbb2"
    frame_color = "#fe8019"
    timeout = 5

[urgency_normal]
    background = "#282828"
    foreground = "#ebdbb2"
    frame_color = "#fe8019"
    timeout = 5

[urgency_critical]
    background = "#cc241d"
    foreground = "#ebdbb2"
    frame_color = "#fe8019"
    timeout = 0
