# Status bar colors — sourced from ~/.tmux.conf
set -g status-left "#[fg=#282828,bg=#{?client_prefix,#cc241d,#458588}] session[#S] "
set -g status-style "bg=#3c3836"
set -g window-status-current-format "#[fg=#fe8019]  #I:#W"
