[urgency_low]
    background = "#0f111a"
    foreground = "#a6accd"
    frame_color = "#82aaff"
    timeout = 5

[urgency_normal]
    background = "#0f111a"
    foreground = "#a6accd"
    frame_color = "#82aaff"
    timeout = 5

[urgency_critical]
    background = "#f07178"
    foreground = "#0f111a"
    frame_color = "#f07178"
    timeout = 0
