# Status bar colors — sourced from ~/.tmux.conf
set -g status-left "#[fg=#2e3440,bg=#{?client_prefix,#bf616a,#81a1c1}] session[#S] "
set -g status-style "bg=#3b4252"
set -g window-status-current-format "#[fg=#88c0d0]  #I:#W"
